server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: jparbros
  password: p0stgres

development:
  <<: *server
  database: curul

test: &test
  <<: *server
  database: curul_test

production:
  <<: *server
  database: curul

cucumber:
  <<: *test
