production:
  solr:
    hostname: solr.parbros.com
    port: 8080
    path: /solr/congracy
    log_level: WARNING

development:
  solr:
    hostname: solr.parbros.com
    port: 8080
    path: /solr/congracy
    log_level: INFO

test:
  solr:
    hostname: 127.0.0.1
    port: 8180
    path: /solr
    log_level: WARNING